sevctl-verify: Return error to main, rather than exiting.
enarx/sevctl pull request #58
Opened 2021-06-16 18:47 UTC by tfanelli-rh

Proposed fix for #53 that includes the omission of an error message if "verify --quiet" is enabled. This allows sevctl verify to be uniform with all other subcommands.

2021-06-18 16:56 UTC, connorkuehl requested changes
@tfanelli-rh Have you tried hoisting the `quiet` flag out to be a top-level argument to sevctl? If the other commands fail, they will propagate errors down to main and main will print them and there's currently no way for the operator to make those commands quiet as well. I think for that reason, we could decouple the `quiet` flag from the `verify` command and make it a top-level switch.

Also, please remove the "." from the end of your commit subject.

2021-06-21 14:25 UTC, tfanelli-rh commented
Latest commit has also addressed #53 by checking if quiet is enabled before printing anything to the console.

2021-06-21 14:31 UTC, tfanelli-rh commented
Latest commit has also addressed #53 by checking if quiet is enabled before printing anything to the console.

2021-06-21 14:31 UTC, tfanelli-rh commented
Latest commit has also addressed #54  by checking if quiet is enabled before printing anything to the console.

2021-06-21 14:39 UTC, connorkuehl requested changes
1. Please rebase and fix the merge conflicts.
2. Is it possible to avoid duplicating the quiet field across all variants of the enum? A quick look at the [StructOpt documentation for subcommands](https://docs.rs/structopt/0.3.21/structopt/#subcommands) suggests we might be able to turn `enum Sevctl` into a `struct Sevctl` and factor the variants out into their own enum. Then the new `struct Sevctl` could expose a top-level `quiet` flag perhaps. 
3. Thanks for taking care of the legend-printing issue! :slightly_smiling_face:

2021-06-21 21:01 UTC, connorkuehl requested changes
Overall, this looks good to me. Just two suggestions inline.

2021-06-22 02:50 UTC, tfanelli-rh commented on src/main.rs
> +            ))
Yea, I see what you mean. I changed this in my latest commit.

2021-06-22 14:15 UTC, connorkuehl approved these changes
Thanks, @tfanelli-rh! Looks good to me.

2021-06-22 14:17 UTC, merged