Remove web server functionality
enarx/sevctl pull request #6
Opened 2020-09-29 15:56 UTC by connorkuehl

Closes #4.

Signed-off-by: Connor Kuehl <ckuehl@redhat.com>

2020-09-29 18:58 UTC, npmccallum requested changes
This PR removes only the server. It doesn't remove the client functionality for that server.

2020-10-05 19:53 UTC, lkatalin approved these changes, later dismissed

2020-10-06 15:46 UTC, connorkuehl commented on src/main.rs
> +        pdh()
Would you consider this a blocker for an alpha release?

2020-10-19 13:39 UTC, npmccallum commented on src/main.rs
> +        pdh()
No.

2020-10-19 13:39 UTC, npmccallum commented
@connorkuehl Please rebase.

2020-10-19 15:02 UTC, connorkuehl commented
Rebased

2020-10-19 15:18 UTC, npmccallum approved these changes

2020-10-19 18:28 UTC, mbestavros approved these changes

2020-10-19 19:01 UTC, merged